CREATE DATABASE IF NOT EXISTS traffic_system DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE traffic_system;

CREATE TABLE IF NOT EXISTS nodes (
  id VARCHAR(20) NOT NULL COMMENT '路口或节点唯一标识',
  name VARCHAR(50) NOT NULL COMMENT '路口名称',
  lat DECIMAL(10, 6) NOT NULL COMMENT '纬度',
  lng DECIMAL(10, 6) NOT NULL COMMENT '经度',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='路网节点表';

CREATE TABLE IF NOT EXISTS traffic_flow (
  id BIGINT AUTO_INCREMENT NOT NULL COMMENT '主键自增 ID',
  node_id VARCHAR(20) NOT NULL COMMENT '关联节点 ID',
  timestamp DATETIME NOT NULL COMMENT '采集时间',
  flow INT NOT NULL COMMENT '交通流量（辆/小时）',
  speed DECIMAL(5, 2) DEFAULT NULL COMMENT '平均车速（km/h）',
  occupancy DECIMAL(5, 4) DEFAULT NULL COMMENT '占有率（0-1）',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
  PRIMARY KEY (id),
  CONSTRAINT fk_traffic_node FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
  INDEX idx_node_time (node_id, timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史交通流量表';

CREATE TABLE IF NOT EXISTS predictions (
  id BIGINT AUTO_INCREMENT NOT NULL COMMENT '主键自增 ID',
  node_id VARCHAR(20) NOT NULL COMMENT '关联节点 ID',
  target_time DATETIME NOT NULL COMMENT '预测目标时间',
  predicted_flow INT NOT NULL COMMENT '预测流量',
  confidence DECIMAL(4, 3) DEFAULT NULL COMMENT '预测置信度',
  model_version VARCHAR(20) DEFAULT 'LST-GCN-v1.2' COMMENT '模型版本',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '生成时间',
  PRIMARY KEY (id),
  CONSTRAINT fk_prediction_node FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
  INDEX idx_node_target (node_id, target_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交通流量预测结果表';

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'SUPER_ADMIN',
  status VARCHAR(20) NOT NULL DEFAULT 'ONLINE',
  preferred_theme VARCHAR(20) NOT NULL DEFAULT 'light',
  prediction_horizon_minutes INT NOT NULL DEFAULT 60,
  sliding_window_steps INT NOT NULL DEFAULT 12,
  retrain_cycle_days INT NOT NULL DEFAULT 7,
  congestion_threshold INT NOT NULL DEFAULT 130,
  auto_signal_control TINYINT(1) NOT NULL DEFAULT 1,
  can_manage_users TINYINT(1) NOT NULL DEFAULT 1,
  can_manage_data TINYINT(1) NOT NULL DEFAULT 1,
  can_manage_models TINYINT(1) NOT NULL DEFAULT 1,
  can_manage_signals TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at DATETIME DEFAULT NULL,
  last_active_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS incidents (
  id VARCHAR(30) NOT NULL PRIMARY KEY,
  type VARCHAR(30) NOT NULL,
  severity VARCHAR(10) NOT NULL,
  location VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  related_node_id VARCHAR(20) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交通事件表';

CREATE TABLE IF NOT EXISTS pems_stations (
  id VARCHAR(30) NOT NULL PRIMARY KEY,
  district VARCHAR(20) DEFAULT NULL,
  freeway VARCHAR(20) DEFAULT NULL,
  direction VARCHAR(20) DEFAULT NULL,
  name VARCHAR(120) NOT NULL,
  lat DECIMAL(10, 6) NOT NULL,
  lng DECIMAL(10, 6) NOT NULL,
  lane_count INT DEFAULT NULL,
  station_type VARCHAR(30) DEFAULT NULL,
  data_source VARCHAR(30) NOT NULL DEFAULT 'PeMS',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='PeMS 站点元数据表';

CREATE TABLE IF NOT EXISTS pems_traffic_flow (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  station_id VARCHAR(30) NOT NULL,
  timestamp DATETIME NOT NULL,
  flow DECIMAL(10, 2) NOT NULL,
  speed DECIMAL(10, 2) DEFAULT NULL,
  occupancy DECIMAL(6, 4) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pems_station FOREIGN KEY (station_id) REFERENCES pems_stations(id) ON DELETE CASCADE,
  INDEX idx_pems_station_time (station_id, timestamp),
  INDEX idx_pems_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='PeMS 实时流量表';
