CREATE DATABASE IF NOT EXISTS traffic_system DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE traffic_system;

CREATE TABLE IF NOT EXISTS nodes (
  id VARCHAR(20) NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  lat DECIMAL(10, 6) NOT NULL,
  lng DECIMAL(10, 6) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='System intersection nodes';

CREATE TABLE IF NOT EXISTS traffic_flow (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  node_id VARCHAR(20) NOT NULL,
  timestamp DATETIME NOT NULL,
  flow INT NOT NULL,
  speed DECIMAL(6, 2) DEFAULT NULL,
  occupancy DECIMAL(6, 4) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_traffic_node FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
  INDEX idx_node_time (node_id, timestamp),
  INDEX idx_time (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='System traffic history';

CREATE TABLE IF NOT EXISTS predictions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  node_id VARCHAR(20) NOT NULL,
  target_time DATETIME NOT NULL,
  predicted_flow INT NOT NULL,
  confidence DECIMAL(4, 3) DEFAULT NULL,
  model_version VARCHAR(40) DEFAULT 'LST-GCN-v1.2',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_prediction_node FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
  INDEX idx_node_target (node_id, target_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Forecast results';

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  password_hash TEXT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
  preferred_theme VARCHAR(20) NOT NULL DEFAULT 'light',
  prediction_horizon_minutes INT NOT NULL DEFAULT 60,
  sliding_window_steps INT NOT NULL DEFAULT 12,
  retrain_cycle_days INT NOT NULL DEFAULT 7,
  congestion_threshold INT NOT NULL DEFAULT 130,
  auto_signal_control TINYINT(1) NOT NULL DEFAULT 1,
  can_manage_users TINYINT(1) NOT NULL DEFAULT 1,
  can_manage_data TINYINT(1) NOT NULL DEFAULT 1,
  can_manage_models TINYINT(1) NOT NULL DEFAULT 1,
  can_manage_signals TINYINT(1) NOT NULL DEFAULT 1,
  session_token VARCHAR(128) DEFAULT NULL,
  session_expires_at DATETIME DEFAULT NULL,
  last_login_at DATETIME DEFAULT NULL,
  last_active_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_users_session_token (session_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Admin users';

CREATE TABLE IF NOT EXISTS incidents (
  id VARCHAR(30) NOT NULL PRIMARY KEY,
  type VARCHAR(30) NOT NULL,
  severity VARCHAR(10) NOT NULL,
  location VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  related_node_id VARCHAR(20) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Traffic incidents';

CREATE TABLE IF NOT EXISTS pems_stations (
  id VARCHAR(30) NOT NULL PRIMARY KEY,
  district VARCHAR(20) DEFAULT NULL,
  freeway VARCHAR(20) DEFAULT NULL,
  direction VARCHAR(20) DEFAULT NULL,
  name VARCHAR(120) NOT NULL,
  lat DECIMAL(10, 6) NOT NULL,
  lng DECIMAL(10, 6) NOT NULL,
  lane_count INT DEFAULT NULL,
  station_type VARCHAR(30) DEFAULT NULL,
  data_source VARCHAR(30) NOT NULL DEFAULT 'PeMS',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='PeMS stations';

CREATE TABLE IF NOT EXISTS pems_traffic_flow (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  station_id VARCHAR(30) NOT NULL,
  timestamp DATETIME NOT NULL,
  flow DECIMAL(10, 2) NOT NULL,
  speed DECIMAL(10, 2) DEFAULT NULL,
  occupancy DECIMAL(6, 4) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pems_station FOREIGN KEY (station_id) REFERENCES pems_stations(id) ON DELETE CASCADE,
  INDEX idx_pems_station_time (station_id, timestamp),
  INDEX idx_pems_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='PeMS traffic history';

CREATE TABLE IF NOT EXISTS pems_node_bindings (
  system_node_id VARCHAR(20) NOT NULL PRIMARY KEY,
  station_id VARCHAR(30) NOT NULL,
  binding_source VARCHAR(30) NOT NULL DEFAULT 'auto',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_pems_binding_station (station_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='PeMS to system-node mapping';
